[package]
name = "module-exp"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib_test"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
